In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv(r'C:\Users\dheof\Desktop\anime.csv')
df

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [3]:
df.isnull().sum()

anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [4]:
df = df.dropna()

In [5]:
df.shape

(12017, 7)

In [6]:
df.isnull().sum()

anime_id    0
name        0
genre       0
type        0
episodes    0
rating      0
members     0
dtype: int64

In [7]:
df = df.reset_index(drop=True)

In [8]:
# Generate item feature matrix
vect = CountVectorizer(tokenizer=lambda x:x.split(', '))
df_genre = vect.fit_transform(df['genre'])
df_genre = pd.DataFrame(df_genre.toarray(), columns=vect.get_feature_names())
df_genre = pd.concat([df[['anime_id', 'name', 'rating']], df_genre], axis=1)
df_genre

,anime_id,name,rating,action,adventure,cars,comedy,dementia,demons,drama,...,shounen ai,slice of life,space,sports,super power,supernatural,thriller,vampire,yaoi,yuri
0,32281,Kimi no Na wa.,9.37,0,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
1,5114,Fullmetal Alchemist: Brotherhood,9.26,1,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,28977,Gintama°,9.25,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,9253,Steins;Gate,9.17,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,9969,Gintama&#039;,9.16,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12012,9316,Toushindai My Lover: Minami tai Mecha-Minami,4.15,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12013,5543,Under World,4.28,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12014,5621,Violence Gekiga David no Hoshi,4.88,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12015,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,4.98,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12016,26081,Yasuji no Pornorama: Yacchimae!!,5.46,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [92]:
df_item_features = df_genre[df_genre['name'].isin([
    'Kimi no Na wa.', 
    'Fullmetal Alchemist: Brotherhood', 
    'Gintama°'])]
df_item_features

,anime_id,name,rating,action,adventure,cars,comedy,dementia,demons,drama,...,shounen ai,slice of life,space,sports,super power,supernatural,thriller,vampire,yaoi,yuri
0,32281,Kimi no Na wa.,9.37,0,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
1,5114,Fullmetal Alchemist: Brotherhood,9.26,1,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,28977,Gintama°,9.25,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## ITEM FEATURE MATRIX WITH RATING

In [93]:
for i in vect.get_feature_names():
    df_item_features[i]= df_item_features['rating'] * df_item_features[i]

df_item_features

,anime_id,name,rating,action,adventure,cars,comedy,dementia,demons,drama,...,shounen ai,slice of life,space,sports,super power,supernatural,thriller,vampire,yaoi,yuri
0,32281,Kimi no Na wa.,9.37,0.00,0.00,0.0,0.00,0.0,0.0,9.37,...,0.0,0.0,0.0,0.0,0.0,9.37,0.0,0.0,0.0,0.0
1,5114,Fullmetal Alchemist: Brotherhood,9.26,9.26,9.26,0.0,0.00,0.0,0.0,9.26,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0
2,28977,Gintama°,9.25,9.25,0.00,0.0,9.25,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0

## CALCULATING USER FEATURE VECTOR

In [94]:
df_item_features[vect.get_feature_names()].sum()

action           18.51
adventure         9.26
cars              0.00
comedy            9.25
dementia          0.00
demons            0.00
drama            18.63
ecchi             0.00
fantasy           9.26
game              0.00
harem             0.00
hentai            0.00
historical        9.25
horror            0.00
josei             0.00
kids              0.00
magic             9.26
martial arts      0.00
mecha             0.00
military          9.26
music             0.00
mystery           0.00
parody            9.25
police            0.00
psychological     0.00
romance           9.37
samurai           9.25
school            9.37
sci-fi            9.25
seinen            0.00
shoujo            0.00
shoujo ai         0.00
shounen          18.51
shounen ai        0.00
slice of life     0.00
space             0.00
sports            0.00
super power       0.00
supernatural      9.37
thriller          0.00
vampire           0.00
yaoi              0.00
yuri              0.00
dtype: float64

In [95]:
user_feature_vector = df_item_features[vect.get_feature_names()].sum()/df_item_features[vect.get_feature_names()].sum().sum()
user_feature_vector

action           0.110805
adventure        0.055433
cars             0.000000
comedy           0.055373
dementia         0.000000
demons           0.000000
drama            0.111523
ecchi            0.000000
fantasy          0.055433
game             0.000000
harem            0.000000
hentai           0.000000
historical       0.055373
horror           0.000000
josei            0.000000
kids             0.000000
magic            0.055433
martial arts     0.000000
mecha            0.000000
military         0.055433
music            0.000000
mystery          0.000000
parody           0.055373
police           0.000000
psychological    0.000000
romance          0.056091
samurai          0.055373
school           0.056091
sci-fi           0.055373
seinen           0.000000
shoujo           0.000000
shoujo ai        0.000000
shounen          0.110805
shounen ai       0.000000
slice of life    0.000000
space            0.000000
sports           0.000000
super power      0.000000
supernatural     0.056091
thriller         0.000000
vampire          0.000000
yaoi             0.000000
yuri             0.000000
dtype: float64

## RECOMMENDATION

In [96]:
recommend = df_genre.loc[~df_genre['name'].isin([
    'Kimi no Na wa.', 
    'Fullmetal Alchemist: Brotherhood', 
    'Gintama°'
    ])]

In [97]:
for i in vect.get_feature_names():
    recommend[i]= recommend[i] * user_feature_vector[i]
recommend

,anime_id,name,rating,action,adventure,cars,comedy,dementia,demons,drama,...,shounen ai,slice of life,space,sports,super power,supernatural,thriller,vampire,yaoi,yuri
3,9253,Steins;Gate,9.17,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,9969,Gintama&#039;,9.16,0.110805,0.000000,0.0,0.055373,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,32935,Haikyuu!!: Karasuno Koukou VS Shiratorizawa Ga...,9.15,0.000000,0.000000,0.0,0.055373,0.0,0.0,0.111523,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,11061,Hunter x Hunter (2011),9.13,0.110805,0.055433,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,820,Ginga Eiyuu Densetsu,9.11,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.111523,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12012,9316,Toushindai My Lover: Minami tai Mecha-Minami,4.15,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12013,5543,Under World,4.28,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12014,5621,Violence Gekiga David no Hoshi,4.88,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12015,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,4.98,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12016,26081,Yasuji no Pornorama: Yacchimae!!,5.46,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## PREDICTED SCORE COLUMN

In [98]:
recommend['predicted_score'] = recommend.drop(columns=['rating', 'anime_id']).sum(axis=1)

In [99]:
recommend

,anime_id,name,rating,action,adventure,cars,comedy,dementia,demons,drama,...,slice of life,space,sports,super power,supernatural,thriller,vampire,yaoi,yuri,predicted_score
3,9253,Steins;Gate,9.17,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.055373
4,9969,Gintama&#039;,9.16,0.110805,0.000000,0.0,0.055373,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.498474
5,32935,Haikyuu!!: Karasuno Koukou VS Shiratorizawa Ga...,9.15,0.000000,0.000000,0.0,0.055373,0.0,0.0,0.111523,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.333792
6,11061,Hunter x Hunter (2011),9.13,0.110805,0.055433,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.277043
7,820,Ginga Eiyuu Densetsu,9.11,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.111523,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.222329
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12012,9316,Toushindai My Lover: Minami tai Mecha-Minami,4.15,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
12013,5543,Under World,4.28,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
12014,5621,Violence Gekiga David no Hoshi,4.88,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
12015,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,4.98,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
12016,26081,Yasuji no Pornorama: Yacchimae!!,5.46,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000

In [100]:
recommend[['name', 'predicted_score']].sort_values('predicted_score', ascending=False).head(20)

                                                   name  predicted_score
5915                                    Asagiri no Miko         0.666926
286                                  Tsubasa: Shunraiki         0.611613
2554                                          Macross 7         0.610835
1558      Fullmetal Alchemist: The Sacred Star of Milos         0.610236
200                                 Fullmetal Alchemist         0.610236
3282  Zero no Tsukaima: Princesses no Rondo Picture ...         0.556181
1071                       Tsubasa Chronicle 2nd Season         0.556181
1845                                      Trinity Seven         0.556121
692                        InuYasha: Tenka Hadou no Ken         0.556121
173                              InuYasha: Kanketsu-hen         0.555462
1347                      Uchuu no Kishi Tekkaman Blade         0.555462
1051                    Arslan Senki (TV): Fuujin Ranbu         0.555462
690                                            InuYasha         0.555462
1762                                 Saber Marionette J         0.555403
3320                  Battle Athletess Daiundoukai (TV)         0.555403
9223                                    Kkomaeosa Ttori         0.554804
151                                             Berserk         0.500808
4050                                     Berserk (2016)         0.500808
3315                                         Ani*Kuri15         0.500748
1315                                           Mai-HiME         0.500748

In [15]:
# # All codes above as a function
# def recommend_me():
#     anime = input('Masukan judul anime yang kamu sukai, pisahkan dengan tanda koma').split(', ')
    
#     import pandas as pd
#     import numpy as np
#     from sklearn.feature_extraction.text import CountVectorizer
    
#     # Create genre dataframe
#     df = pd.read_csv(r'C:\Users\dheof\Desktop\anime.csv')
#     df = df.loc[:, ['anime_id', 'name', 'genre', 'rating']].dropna().reset_index(drop=True)
#     vect = CountVectorizer(tokenizer=lambda x:x.split(', '))
#     df_genre = vect.fit_transform(df['genre'])
#     df_genre = pd.DataFrame(df_genre.toarray(), columns=vect.get_feature_names())
#     df_genre = pd.concat([df[['anime_id', 'name', 'rating']], df_genre],axis=1)
    
#     # User feature vector
#     df_choice = df_genre[df_genre['name'].isin(anime)]
    
#     for i in vect.get_feature_names():
#         df_choice[i]= df_choice['rating']*df_choice[i]
    
#     user_feature_vector = df_choice[vect.get_feature_names()].sum()/df_choice[vect.get_feature_names()].sum().sum()

#     # Predict score
#     df_recommend = df_genre[~df_genre['name'].isin(anime)].drop(columns='rating')
    
#     for i in vect.get_feature_names():
#         df_recommend[i] = df_recommend[i]*user_feature_vector[i]
        
#     df_recommend['predicted_score'] = df_recommend.drop(columns=['anime_id']).sum(axis=1)
    
#     return df_recommend[['name', 'predicted_score']].sort_values('predicted_score', ascending=False).head(20)

# CONTENT BASED FILTERING MULTIPLE USERS

In [16]:
search = 'One'
  
result = df['name'].str.startswith(search, na = False) 
df[result]

,anime_id,name,genre,type,episodes,rating,members
23,30276,One Punch Man,"Action, Comedy, Parody, Sci-Fi, Seinen, Super ...",TV,12,8.82,552458
74,21,One Piece,"Action, Adventure, Comedy, Drama, Fantasy, Sho...",TV,Unknown,8.58,504862
143,4155,One Piece Film: Strong World,"Action, Adventure, Comedy, Drama, Fantasy, Sho...",Movie,1,8.42,85020
149,5040,One Outs,"Psychological, Seinen, Sports",TV,25,8.41,83056
163,12859,One Piece Film: Z,"Action, Adventure, Comedy, Drama, Fantasy, Sho...",Movie,1,8.39,76051
...,...,...,...,...,...,...,...
5253,13283,One Off,Slice of Life,OVA,4,6.50,9299
7602,675,One: Kagayaku Kisetsu e,"Drama, Supernatural",OVA,4,5.24,2285
9812,32763,One and Three Four,Music,Music,1,4.51,89
9813,14947,Onegai My Melody: Yuu &amp; Ai,"Comedy, Fantasy",Movie,1,5.73,271
11343,1113,One: Kagayaku Kisetsu e - True Stories,Hentai,OVA,3,6.37,1934

## USER ITEM RATING MATRIX

In [56]:
user_item_rating = pd.DataFrame({
    'User' : ['User 1', 'User 2', 'User 3', 'User 4'],
    'One Punch Man (30276)' : [7, 8, 9, 6],
    'One Piece (21)' : [6, 8, 0, 9],
    'One Piece Film: Strong World (4155)' : [0, 0, 7, 8],
    'One Outs(5040)' : [6, 0, 7, 9]
})

In [57]:
user_item_rating

,User,One Punch Man (30276),One Piece (21),One Piece Film: Strong World (4155),One Outs(5040)
0,User 1,7,6,0,6
1,User 2,8,8,0,0
2,User 3,9,0,7,7
3,User 4,6,9,8,9

## VECTORIZER (ITEM FEATURE MATRIX)

In [19]:
# Generate item feature matrix
vect = CountVectorizer(tokenizer=lambda x:x.split(', '))
df_genre = vect.fit_transform(df['genre'])
df_genre = pd.DataFrame(df_genre.toarray(), columns=vect.get_feature_names())
df_genre = pd.concat([df[['anime_id', 'name', 'rating']], df_genre], axis=1)
df_genre

,anime_id,name,rating,action,adventure,cars,comedy,dementia,demons,drama,...,shounen ai,slice of life,space,sports,super power,supernatural,thriller,vampire,yaoi,yuri
0,32281,Kimi no Na wa.,9.37,0,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
1,5114,Fullmetal Alchemist: Brotherhood,9.26,1,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,28977,Gintama°,9.25,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,9253,Steins;Gate,9.17,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,9969,Gintama&#039;,9.16,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12012,9316,Toushindai My Lover: Minami tai Mecha-Minami,4.15,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12013,5543,Under World,4.28,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12014,5621,Violence Gekiga David no Hoshi,4.88,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12015,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,4.98,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12016,26081,Yasuji no Pornorama: Yacchimae!!,5.46,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## CHOOSING 4 ANIME

In [20]:
item_features = df_genre[df_genre['name'].isin([
    'One Punch Man', 
    'One Piece', 
    'One Piece Film: Strong World', 
    'One Outs'
])]
item_features

,anime_id,name,rating,action,adventure,cars,comedy,dementia,demons,drama,...,shounen ai,slice of life,space,sports,super power,supernatural,thriller,vampire,yaoi,yuri
23,30276,One Punch Man,8.82,1,0,0,1,0,0,0,...,0,0,0,0,1,1,0,0,0,0
74,21,One Piece,8.58,1,1,0,1,0,0,1,...,0,0,0,0,1,0,0,0,0,0
143,4155,One Piece Film: Strong World,8.42,1,1,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
149,5040,One Outs,8.41,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

## ITEM FEATURE MATRIX WITH RATING

In [21]:
for i in vect.get_feature_names():
    item_features[i] = item_features['rating'] * item_features[i]

item_features

,anime_id,name,rating,action,adventure,cars,comedy,dementia,demons,drama,...,shounen ai,slice of life,space,sports,super power,supernatural,thriller,vampire,yaoi,yuri
23,30276,One Punch Man,8.82,8.82,0.00,0.0,8.82,0.0,0.0,0.00,...,0.0,0.0,0.0,0.00,8.82,8.82,0.0,0.0,0.0,0.0
74,21,One Piece,8.58,8.58,8.58,0.0,8.58,0.0,0.0,8.58,...,0.0,0.0,0.0,0.00,8.58,0.00,0.0,0.0,0.0,0.0
143,4155,One Piece Film: Strong World,8.42,8.42,8.42,0.0,8.42,0.0,0.0,8.42,...,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0
149,5040,One Outs,8.41,0.00,0.00,0.0,0.00,0.0,0.0,0.00,...,0.0,0.0,0.0,8.41,0.00,0.00,0.0,0.0,0.0,0.0

## USER FEATURE VECTOR

In [91]:
user_feature_vector = item_features[vect.get_feature_names()].sum() / item_features[vect.get_feature_names()].sum().sum()
user_feature_vector

action           0.130701
adventure        0.086054
cars             0.000000
comedy           0.130701
dementia         0.000000
demons           0.000000
drama            0.086054
ecchi            0.000000
fantasy          0.086054
game             0.000000
harem            0.000000
hentai           0.000000
historical       0.000000
horror           0.000000
josei            0.000000
kids             0.000000
magic            0.000000
martial arts     0.000000
mecha            0.000000
military         0.000000
music            0.000000
mystery          0.000000
parody           0.044647
police           0.000000
psychological    0.042572
romance          0.000000
samurai          0.000000
school           0.000000
sci-fi           0.044647
seinen           0.087218
shoujo           0.000000
shoujo ai        0.000000
shounen          0.086054
shounen ai       0.000000
slice of life    0.000000
space            0.000000
sports           0.042572
super power      0.088079
supernatural     0.044647
thriller         0.000000
vampire          0.000000
yaoi             0.000000
yuri             0.000000
dtype: float64

## RECOMMENDATION

In [58]:
user_item_rating

,User,One Punch Man (30276),One Piece (21),One Piece Film: Strong World (4155),One Outs(5040)
0,User 1,7,6,0,6
1,User 2,8,8,0,0
2,User 3,9,0,7,7
3,User 4,6,9,8,9

### RECOMMENDATION FOR USER 1

In [59]:
recommend_user1 = df_genre.loc[
    ~df_genre['anime_id'].isin([
        30276,
        21,
        5040
        ])
]

In [60]:
for i in vect.get_feature_names():
    recommend_user1[i] = recommend_user1[i] * user_feature_vector[i]

recommend_user1

,anime_id,name,rating,action,adventure,cars,comedy,dementia,demons,drama,...,shounen ai,slice of life,space,sports,super power,supernatural,thriller,vampire,yaoi,yuri
0,32281,Kimi no Na wa.,9.37,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.086054,...,0.0,0.0,0.0,0.0,0.0,0.044647,0.0,0.0,0.0,0.0
1,5114,Fullmetal Alchemist: Brotherhood,9.26,0.130701,0.086054,0.0,0.000000,0.0,0.0,0.086054,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
2,28977,Gintama°,9.25,0.130701,0.000000,0.0,0.130701,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
3,9253,Steins;Gate,9.17,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4,9969,Gintama&#039;,9.16,0.130701,0.000000,0.0,0.130701,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12012,9316,Toushindai My Lover: Minami tai Mecha-Minami,4.15,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
12013,5543,Under World,4.28,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
12014,5621,Violence Gekiga David no Hoshi,4.88,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
12015,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,4.98,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
12016,26081,Yasuji no Pornorama: Yacchimae!!,5.46,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0

In [26]:
# recommend_user1['Predicted Score'] = recommend.drop(columns = ['rating', 'anime_id']).sum(axis=1)

In [61]:
recommend_user1['User 1'] = recommend_user1.drop(columns= ['rating', 'anime_id']).sum(axis = 1)

In [62]:
recommend_user1

,anime_id,name,rating,action,adventure,cars,comedy,dementia,demons,drama,...,slice of life,space,sports,super power,supernatural,thriller,vampire,yaoi,yuri,User 1
0,32281,Kimi no Na wa.,9.37,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.086054,...,0.0,0.0,0.0,0.0,0.044647,0.0,0.0,0.0,0.0,0.130701
1,5114,Fullmetal Alchemist: Brotherhood,9.26,0.130701,0.086054,0.0,0.000000,0.0,0.0,0.086054,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.474918
2,28977,Gintama°,9.25,0.130701,0.000000,0.0,0.130701,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.436750
3,9253,Steins;Gate,9.17,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.044647
4,9969,Gintama&#039;,9.16,0.130701,0.000000,0.0,0.130701,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.436750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12012,9316,Toushindai My Lover: Minami tai Mecha-Minami,4.15,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
12013,5543,Under World,4.28,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
12014,5621,Violence Gekiga David no Hoshi,4.88,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
12015,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,4.98,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
12016,26081,Yasuji no Pornorama: Yacchimae!!,5.46,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000

In [30]:
# recommend_user1[['name', 'User 1']].sort_values('User 1', ascending=False).head(10)

In [63]:
recommend_user1[['anime_id', 'name', 'User 1']].sort_values('User 1', ascending=False).head(10)

       anime_id                                               name    User 1
5915        231                                    Asagiri no Miko  0.696937
231       19123  One Piece: Episode of Merry - Mou Hitori no Na...  0.693698
241       15323  One Piece: Episode of Nami - Koukaishi no Nami...  0.693698
896       31289  One Piece: Episode of Sabo - 3 Kyoudai no Kizu...  0.693698
3288        891       Dragon Ball Movie 2: Majinjou no Nemuri Hime  0.652291
4442        225                                     Dragon Ball GT  0.652291
3051        892         Dragon Ball Movie 3: Makafushigi Daibouken  0.652291
1931      12231                    Dragon Ball: Episode of Bardock  0.652291
2184        893            Dragon Ball Movie 4: Saikyou e no Michi  0.652291
10704      7419                Wrestler Gundan Seisenshi Robin Jr.  0.610883

### RECOMMEND FOR USER 2

In [64]:
user_item_rating

,User,One Punch Man (30276),One Piece (21),One Piece Film: Strong World (4155),One Outs(5040)
0,User 1,7,6,0,6
1,User 2,8,8,0,0
2,User 3,9,0,7,7
3,User 4,6,9,8,9

In [65]:
recommend_user2 = df_genre.loc[
    ~df_genre['name'].isin([
        30276,
        21,
        ])
]

In [66]:
for i in vect.get_feature_names():
    recommend_user2[i] = recommend_user2[i] * user_feature_vector[i]

recommend_user2

,anime_id,name,rating,action,adventure,cars,comedy,dementia,demons,drama,...,shounen ai,slice of life,space,sports,super power,supernatural,thriller,vampire,yaoi,yuri
0,32281,Kimi no Na wa.,9.37,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.086054,...,0.0,0.0,0.0,0.0,0.0,0.044647,0.0,0.0,0.0,0.0
1,5114,Fullmetal Alchemist: Brotherhood,9.26,0.130701,0.086054,0.0,0.000000,0.0,0.0,0.086054,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
2,28977,Gintama°,9.25,0.130701,0.000000,0.0,0.130701,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
3,9253,Steins;Gate,9.17,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4,9969,Gintama&#039;,9.16,0.130701,0.000000,0.0,0.130701,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12012,9316,Toushindai My Lover: Minami tai Mecha-Minami,4.15,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
12013,5543,Under World,4.28,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
12014,5621,Violence Gekiga David no Hoshi,4.88,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
12015,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,4.98,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
12016,26081,Yasuji no Pornorama: Yacchimae!!,5.46,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0

In [67]:
recommend_user2['User 2'] = recommend_user2.drop(columns= ['rating', 'anime_id']).sum(axis=1)

In [68]:
recommend_user2

,anime_id,name,rating,action,adventure,cars,comedy,dementia,demons,drama,...,slice of life,space,sports,super power,supernatural,thriller,vampire,yaoi,yuri,User 2
0,32281,Kimi no Na wa.,9.37,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.086054,...,0.0,0.0,0.0,0.0,0.044647,0.0,0.0,0.0,0.0,0.130701
1,5114,Fullmetal Alchemist: Brotherhood,9.26,0.130701,0.086054,0.0,0.000000,0.0,0.0,0.086054,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.474918
2,28977,Gintama°,9.25,0.130701,0.000000,0.0,0.130701,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.436750
3,9253,Steins;Gate,9.17,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.044647
4,9969,Gintama&#039;,9.16,0.130701,0.000000,0.0,0.130701,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.436750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12012,9316,Toushindai My Lover: Minami tai Mecha-Minami,4.15,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
12013,5543,Under World,4.28,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
12014,5621,Violence Gekiga David no Hoshi,4.88,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
12015,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,4.98,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
12016,26081,Yasuji no Pornorama: Yacchimae!!,5.46,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000

In [69]:
recommend_user2[['anime_id', 'name', 'User 2']].sort_values('User 2', ascending=False).head(10)

      anime_id                                               name    User 2
5915       231                                    Asagiri no Miko  0.696937
231      19123  One Piece: Episode of Merry - Mou Hitori no Na...  0.693698
74          21                                          One Piece  0.693698
241      15323  One Piece: Episode of Nami - Koukaishi no Nami...  0.693698
896      31289  One Piece: Episode of Sabo - 3 Kyoudai no Kizu...  0.693698
3051       892         Dragon Ball Movie 3: Makafushigi Daibouken  0.652291
2184       893            Dragon Ball Movie 4: Saikyou e no Michi  0.652291
1931     12231                    Dragon Ball: Episode of Bardock  0.652291
3288       891       Dragon Ball Movie 2: Majinjou no Nemuri Hime  0.652291
4442       225                                     Dragon Ball GT  0.652291

## RECOMMENDATION USER 3

In [70]:
user_item_rating

,User,One Punch Man (30276),One Piece (21),One Piece Film: Strong World (4155),One Outs(5040)
0,User 1,7,6,0,6
1,User 2,8,8,0,0
2,User 3,9,0,7,7
3,User 4,6,9,8,9

In [1]:
recommend_user3 = df_genre.loc[
    ~df_genre['name'].isin([
        30276,
        4155,
        5040
        ])
]

NameError: name 'df_genre' is not defined

In [ ]:
for i in vect.get_feature_names():
    recommend_user3[i] = recommend_user3[i] * user_feature_vector[i]

recommend_user3

,anime_id,name,rating,action,adventure,cars,comedy,dementia,demons,drama,...,shounen ai,slice of life,space,sports,super power,supernatural,thriller,vampire,yaoi,yuri
0,32281,Kimi no Na wa.,9.37,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.086054,...,0.0,0.0,0.0,0.0,0.0,0.044647,0.0,0.0,0.0,0.0
1,5114,Fullmetal Alchemist: Brotherhood,9.26,0.130701,0.086054,0.0,0.000000,0.0,0.0,0.086054,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
2,28977,Gintama°,9.25,0.130701,0.000000,0.0,0.130701,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
3,9253,Steins;Gate,9.17,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4,9969,Gintama&#039;,9.16,0.130701,0.000000,0.0,0.130701,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12012,9316,Toushindai My Lover: Minami tai Mecha-Minami,4.15,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
12013,5543,Under World,4.28,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
12014,5621,Violence Gekiga David no Hoshi,4.88,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
12015,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,4.98,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
12016,26081,Yasuji no Pornorama: Yacchimae!!,5.46,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0

In [ ]:
recommend_user3['User 3'] = recommend_user3.drop(columns= ['rating', 'anime_id']).sum(axis = 1)

In [ ]:
recommend_user3[['anime_id', 'name', 'User 3']].sort_values('User 3', ascending=False).head(10)

      anime_id                                               name    User 3
5915       231                                    Asagiri no Miko  0.696937
231      19123  One Piece: Episode of Merry - Mou Hitori no Na...  0.693698
74          21                                          One Piece  0.693698
241      15323  One Piece: Episode of Nami - Koukaishi no Nami...  0.693698
896      31289  One Piece: Episode of Sabo - 3 Kyoudai no Kizu...  0.693698
3051       892         Dragon Ball Movie 3: Makafushigi Daibouken  0.652291
2184       893            Dragon Ball Movie 4: Saikyou e no Michi  0.652291
1931     12231                    Dragon Ball: Episode of Bardock  0.652291
3288       891       Dragon Ball Movie 2: Majinjou no Nemuri Hime  0.652291
4442       225                                     Dragon Ball GT  0.652291

### RECOMMEND USER 4

In [ ]:
user_item_rating

,User,One Punch Man (30276),One Piece (21),One Piece Film: Strong World (4155),One Outs(5040)
0,User 1,7,6,0,6
1,User 2,8,8,0,0
2,User 3,9,0,7,7
3,User 4,6,9,8,9

In [ ]:
recommend_user4 = df_genre.loc[
    ~df_genre['anime_id'].isin([
        30276,
        21,
        4155,
        5040
    ])
]

In [ ]:
for i in vect.get_feature_names():
    recommend_user4[i] = recommend_user4[i] * user_feature_vector[i]

recommend_user4

,anime_id,name,rating,action,adventure,cars,comedy,dementia,demons,drama,...,shounen ai,slice of life,space,sports,super power,supernatural,thriller,vampire,yaoi,yuri
0,32281,Kimi no Na wa.,9.37,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.086054,...,0.0,0.0,0.0,0.0,0.0,0.044647,0.0,0.0,0.0,0.0
1,5114,Fullmetal Alchemist: Brotherhood,9.26,0.130701,0.086054,0.0,0.000000,0.0,0.0,0.086054,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
2,28977,Gintama°,9.25,0.130701,0.000000,0.0,0.130701,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
3,9253,Steins;Gate,9.17,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4,9969,Gintama&#039;,9.16,0.130701,0.000000,0.0,0.130701,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12012,9316,Toushindai My Lover: Minami tai Mecha-Minami,4.15,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
12013,5543,Under World,4.28,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
12014,5621,Violence Gekiga David no Hoshi,4.88,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
12015,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,4.98,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
12016,26081,Yasuji no Pornorama: Yacchimae!!,5.46,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0

In [ ]:
recommend_user4['User 4'] = recommend_user4.drop(columns = ['rating', 'anime_id']).sum(axis=1)

In [ ]:
recommend_user4

,anime_id,name,rating,action,adventure,cars,comedy,dementia,demons,drama,...,slice of life,space,sports,super power,supernatural,thriller,vampire,yaoi,yuri,User 4
0,32281,Kimi no Na wa.,9.37,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.086054,...,0.0,0.0,0.0,0.0,0.044647,0.0,0.0,0.0,0.0,0.130701
1,5114,Fullmetal Alchemist: Brotherhood,9.26,0.130701,0.086054,0.0,0.000000,0.0,0.0,0.086054,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.474918
2,28977,Gintama°,9.25,0.130701,0.000000,0.0,0.130701,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.436750
3,9253,Steins;Gate,9.17,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.044647
4,9969,Gintama&#039;,9.16,0.130701,0.000000,0.0,0.130701,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.436750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12012,9316,Toushindai My Lover: Minami tai Mecha-Minami,4.15,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
12013,5543,Under World,4.28,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
12014,5621,Violence Gekiga David no Hoshi,4.88,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
12015,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,4.98,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
12016,26081,Yasuji no Pornorama: Yacchimae!!,5.46,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000

In [ ]:
recommend_user4[['anime_id', 'name', 'User 4']].sort_values('User 4', ascending = False).head(10)

       anime_id                                               name    User 4
5915        231                                    Asagiri no Miko  0.696937
231       19123  One Piece: Episode of Merry - Mou Hitori no Na...  0.693698
896       31289  One Piece: Episode of Sabo - 3 Kyoudai no Kizu...  0.693698
241       15323  One Piece: Episode of Nami - Koukaishi no Nami...  0.693698
2184        893            Dragon Ball Movie 4: Saikyou e no Michi  0.652291
1931      12231                    Dragon Ball: Episode of Bardock  0.652291
4442        225                                     Dragon Ball GT  0.652291
3288        891       Dragon Ball Movie 2: Majinjou no Nemuri Hime  0.652291
3051        892         Dragon Ball Movie 3: Makafushigi Daibouken  0.652291
10704      7419                Wrestler Gundan Seisenshi Robin Jr.  0.610883

In [ ]:
# for i in vect.get_feature_names():
#     df_choice[i]= df_choice['rating'] * df_choice[i]

# df_choice
# for i in function in vect in ge_get CountVectorizer:
#     for i in for in function:

# import pandas as pd
# # import numpy as np
# from sklearn.pd.concat